# SPDX-PackageName: vad-ipmap
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://codeberg.org/rfinnie/vad-ipmap
# SPDX-FileComment: Woodpecker CI ci workflow
# SPDX-FileCopyrightText: © 2026 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0
---
when:
  - event: ["push", "pull_request", "manual"]
labels:
  platform: "linux/amd64"
steps:
  - name: "CI"
    image: "debian"
    commands: |
      set -x

      mkdir -p /etc/apt/apt.conf.d
      cat <<"EOM" >/etc/apt/apt.conf.d/99proxy
      Acquire::http::Proxy "http://deb-proxy.snowman.lan:8000";
      Acquire::https::Proxy "http://deb-proxy.snowman.lan:8000";
      EOM

      apt update
      apt -y install bzip2 python3 python3-yaml

      .ci/bin/script-tests
  - name: "Notify Mastodon if failure"
    when:
      - status: ["failure"]
    image: "woodpeckerci/plugin-mastodon-post"
    settings:
      server_url: "https://m29.us"
      access_token:
        from_secret: "m29_token"
      status: |
        🪿 🪿 🪿 FAILURE: {{ CI_REPO }} 🪿 🪿 🪿
        Workflow: {{ CI_WORKFLOW_NAME }} ({{ CI_PIPELINE_EVENT }} on {{ CI_COMMIT_REF }})

        Pipeline: {{ CI_PIPELINE_URL }}
        Commit: {{ CI_PIPELINE_FORGE_URL }}
