# SPDX-PackageName: vad-ipmap
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://forge.colobox.com/rfinnie/vad-ipmap
# SPDX-FileComment: Woodpecker CI ci workflow
# SPDX-FileCopyrightText: © 2026 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0
---
when:
  - event: ["push", "pull_request", "manual"]
labels:
  platform: "linux/amd64"
clone:
  git:
    image: "docker.io/woodpeckerci/plugin-git:latest@sha256:ebde4a4d07e0e24b630082484d192890dd4f6d442d90bf5466f0763860f83652"  # 2026-05-28
steps:
  - name: "CI"
    image: "docker.io/library/debian:trixie@sha256:4ae67669760b807c19f23902a3fd7c121a6a70cf2ae709035674b23e712e4d62"  # 2026-05-19
    commands: |
      set -x

      mkdir -p /etc/apt/apt.conf.d
      cat <<"EOM" >/etc/apt/apt.conf.d/99proxy
      Acquire::http::Proxy "http://deb-proxy.snowman.lan:8000";
      Acquire::https::Proxy "http://deb-proxy.snowman.lan:8000";
      EOM

      apt update
      apt -y install bzip2 python3 python3-yaml

      .ci/bin/script-tests
  - name: "Notify Mastodon if failure"
    when:
      - status: ["failure"]
    image: "docker.io/woodpeckerci/plugin-mastodon-post:latest@sha256:456597681cff794b6ddb7b085ce95c42a18301e512503898c4abdaa1080e7e4c"  # 2026-04-19
    settings:
      server_url: "https://m29.us"
      access_token:
        from_secret: "m29_token"
      status: |
        🪿 🪿 🪿 FAILURE: {{ CI_REPO }} 🪿 🪿 🪿
        Workflow: {{ CI_WORKFLOW_NAME }} ({{ CI_PIPELINE_EVENT }} on {{ CI_COMMIT_REF }})

        Pipeline: {{ CI_PIPELINE_URL }}
        Commit: {{ CI_PIPELINE_FORGE_URL }}
